def commitFullHash = ''
def commitShortHash = ''
def currentDate = new Date()

node {
  stage ('Checkout') {
     commitFullHash = checkout(scm).GIT_COMMIT
     commitShortHash = commitFullHash.take(7)
     buildArg = "--build-arg GIT_COMMIT=$commitShortHash -f ./Dockerfile ."
     echo buildArg
  }
  stage ('Build multiconnector') {
    docker.build('eenemanoy/multi-connector', buildArg)
  }
  stage ('DockerPublish') {
    String currentTimeFormat= currentDate.format("yyyy-MM-dd_HHMMss")
    docker.withRegistry('https://registry-1.docker.io/v2/', 'eeneman-dockerhub') {
      docker.image('eenemanoy/multi-connector').push(currentTimeFormat)
      docker.image('eenemanoy/multi-connector').push(currentTimeFormat+'-test')
    }
  }
}